name: Merge PRs

on:
  schedule:
    - cron: '0 9 * * 0'  # This runs every Sunday at 9 AM
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  request-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Request manual approval
        uses: actions/github-script@v6
        id: approve
        with:
          script: |
            const { github, context } = require('@actions/github');
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const runId = context.runId;

            // Create a new issue for approval
            const { data: issue } = await github.issues.create({
              owner,
              repo,
              title: `Approval needed for Merge PRs`,
              body: `Please approve this workflow run: [Approval Link](https://github.com/${owner}/${repo}/actions/runs/${runId})`
            });

            return issue.number;
          result-encoding: string
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Wait for approval
        uses: actions/github-script@v6
        id: wait-approval
        with:
          script: |
            const { github, context } = require('@actions/github');
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = parseInt('${{ steps.approve.outputs.result }}', 10);

            let approved = false;
            while (!approved) {
              const { data: issue } = await github.issues.get({
                owner,
                repo,
                issue_number
              });

              if (issue.state === 'closed') {
                approved = true;
              } else {
                console.log('Waiting for approval...');
                await new Promise(resolve => setTimeout(resolve, 60000)); // Wait 1 minute
              }
            }

  merge-prs:
    runs-on: ubuntu-latest
    needs: request-approval
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge all open pull requests
        uses: actions/github-script@v6
        with:
          script: |
            const { github, context } = require('@actions/github');
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const { data: pullRequests } = await github.pulls.list({
              owner,
              repo,
              state: 'open'
            });

            for (const pr of pullRequests) {
              await github.pulls.merge({
                owner,
                repo,
                pull_number: pr.number,
                merge_method: 'merge'
              });
              console.log(`Merged PR #${pr.number}`);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}