name: telegram notification
on:
  push:
    branches-ignore:
      - 'main'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@2efd23283ae25229a0b4d315d5d33f73b346ef99 #v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          disable_web_page_preview: true
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}