name: Weekly Release

on:
  schedule:
    - cron: '0 9 * * 0' # Every Sunday at 09:00 UTC
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: cli/gh-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the current date
        id: date
        run: echo "current_date=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Create the release
        run: gh release create "${{ env.current_date }}" --title "${{ env.current_date }}" --draft

  wait-for-approval:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Approve the release
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: approve-release

  finalize-release:
    runs-on: ubuntu-latest
    needs: wait-for-approval
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: cli/gh-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the current date
        id: date
        run: echo "current_date=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Publish the release
        run: gh release edit "${{ env.current_date }}" --draft=false